jobs:
- deployment: Destroy
  displayName: terraform destroy
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - task: TerraformInstaller@1
          displayName: Terraform Client Installer
          inputs:
            terraformVersion: '1.6.6'

        - script: terraform init
          workingDirectory: terraform
          displayName: Terraform Init
          env:
            TF_TOKEN_app_terraform_io: $(TFC_TOKEN)

        - script: terraform destroy -auto-approve -var-file=env/$(environment).tfvars
          workingDirectory: terraform
          displayName: Terraform Destroy
          env:
            TF_TOKEN_app_terraform_io: $(TFC_TOKEN)
