# Checks formatting, providers, and syntax.
jobs:
- job: Validate
  displayName: terraform validate
  steps:
  - checkout: self

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.6.6'
    displayName: Terraform Client Installation

  - script: terraform fmt -check -recursive -diff -no-color
    workingDirectory: terraform
    displayName: Terraform Format Check

  - script: |
      terraform init -backend=false
      terraform validate
    workingDirectory: terraform
    displayName: Terraform Validate
    env:
      TF_TOKEN_app_terraform_io: $(TFC_TOKEN)
